### ISSUE TITLE
fade in out effect and adjust the speed

### ISSUE THREAD

**Issue by arhoy** [AndreasFaust/react-ticker#14]
Hello I am trying to create a fade in and out effect like so
https://www.netlify.com/ 

I would also like to adjust to speed. How can I do this?

**Comment by AndreasFaust** [comment]
That is easy. Just use pseudo-elements to paint gradients on each side of your ticker-container.

```css
.ticker {
  position: relative;
}

.ticker::before,
.ticker::after {
  content: '';
  display: block;
  position: absolute;
  top: 0;
  bottom: 0;
  width: 25vw;
}
.ticker::before {
  left: 0;
  background-image: linear-gradient(to right, white, transparent)
}
.ticker::after {
  right: 0;
  background-image: linear-gradient(to left, white, transparent)
}
```

The Ticker-Speed can be controlled via the `speed`-prop, like described in the docs.

If this answer and `react-ticker` are helpful for you, consider supporting my open-source work by giving this library a star.
